Set GPG_TTY
This fixes the following git commit signing error that is caused by an
locked key where no password prompt is shown:

```
error: gpg failed to sign the data
fatal: failed to write commit object
```